### PR TITLE
fix: cors and vue-cli-service serve issue fixes

### LINKED ISSUE #398: intermittent CORS and 404 errors in user agent
- vue cli service serve is broken after introduction of public path
- need CORS headers in http server

### PR DESCRIPTION
**Pull request by sudeshrshetty**
- changed vue config public path from '/wallet' to '/wallet/' to follow
vue public path convention. (This was causing `//` in wallet worker URLs
causing 404 errors in vue-cli-service serve)
- fixed intermittent CORS issue in wallet iframes
- closes #398

Signed-off-by: sudesh.shetty <sudesh.shetty@securekey.com>

### CODE REVIEW

File: cmd/http-server/startcmd/start.go [hunk 1]
```diff
@@ -654,11 +655,18 @@ func startHTTPServer(parameters *httpServerParameters) error {
 		return fmt.Errorf("failed to configure router: %w", err)
 	}
 
+	handler := cors.New(
+		cors.Options{
+			AllowedMethods: []string{http.MethodGet, http.MethodPost, http.MethodDelete, http.MethodHead},
```
Comment (llorllale) [inline cmd/http-server/startcmd/start.go:660]: Delete? Head? Do we need those?

**Review by llorllale — APPROVED** [review]

File: cmd/http-server/startcmd/start.go (hunk 1 above)
Comment (sudeshrshetty) [reply cmd/http-server/startcmd/start.go]: deleted 'delete' & 'head', we aren't using both for now.

**Review by troyronda — APPROVED** [review]
