### PR TITLE
fix: Added default SDS URL and agent username TrustBloc agent opts

### LINKED ISSUE #296: Add default SDS and agent username TrustBloc startup opts
The SDS default startup opt in particular will allow user-agent Javascript code to be run with "npm run serve" without SDS-related runtime errors. The agent username is needed for SDS, and shouldn't be blank either.

### PR DESCRIPTION
**Pull request by DRK3**
closes #296

- user-agent JavaScript code can now be run with "npm run serve" without SDS-related runtime errors.

- Added blank SDS URL check to sdscomm. This prevents an unintuitive error message from being produced.

- Added blank agent username check to sdscomm.

Signed-off-by: Derek Trider <Derek.Trider@securekey.com>

### CODE REVIEW

File: cmd/user-agent/src/main.js [hunk 1]
```diff
@@ -69,6 +69,8 @@ let defaultTrustBlocStartupOpts = {
     'log-level': 'debug',
     walletMediatorURL: '',
     credentialMediatorURL: '',
+    agentUsername: 'user-agent',
+    sdsServerURL: 'https://localhost:8072/encrypted-data-vaults'
```
Comment (sudeshrshetty) [inline cmd/user-agent/src/main.js:73]: don't hardcode SDS URL in default opts, leave it as empty.

File: pkg/controller/command/didclient/command.go [hunk 2]
```diff
@@ -149,9 +150,13 @@ func (c *Command) SaveDID(_ io.Writer, req io.Reader) command.Error {
 }
 
 func (c *Command) saveDID(didDataToStore *sdscomm.DIDDocData) command.Error {
-	sdsComm := sdscomm.New(c.sdsServerURL, c.agentUsername)
+	sdsComm, err := sdscomm.New(c.sdsServerURL, c.agentUsername)
```
Comment (sudeshrshetty) [inline pkg/controller/command/didclient/command.go:153]: why are you creating new sdsComm instance everytime? looks like serverURL & agentUsername are always same here?

File: pkg/controller/command/sdscomm/sdscomm.go [hunk 3]
```diff
@@ -34,12 +38,21 @@ type DIDDocData struct {
 	Name     string          `json:"name,omitempty"`
 }
 
-func New(sdsServerURL, agentUsername string) *SDSComm {
+func New(sdsServerURL, agentUsername string) (*SDSComm, error) {
+	logger.Infof("!!!DEREK about to check if the provided SDS URL is blank.")
```
Comment (sudeshrshetty) [inline pkg/controller/command/sdscomm/sdscomm.go:42]: `DEREK` ???

File: cmd/user-agent/src/main.js (hunk 1 above)
Comment (llorllale) [reply cmd/user-agent/src/main.js:73]: @sudeshrshetty how is this different than the hard-coding in `defaultAriesStartupOpts` or the existing keys in `defaultTrustBlocStartupOpts`?

Part of this change also makes the SDS URL mandatory otherwise it will fail. Adding a toggle to choose local or remote storage is still a ways off into the future.

File: pkg/controller/command/sdscomm/sdscomm.go (hunk 3 above)
Comment (DRK3) [reply pkg/controller/command/sdscomm/sdscomm.go]: Oops... fixed :)

File: pkg/controller/command/didclient/command.go (hunk 2 above)
Comment (DRK3) [reply pkg/controller/command/didclient/command.go:153]: Every time the go code executes it creates a new Command object. Is there a way I can avoid this?

File: cmd/user-agent/src/main.js (hunk 1 above)
Comment (sudeshrshetty) [reply cmd/user-agent/src/main.js:73]: Default ops won't work. Even walletMediatorURL is mandatory, we didn't set it. 

If we want edge-agent to work with default ops, then we need to initialize all required opts properly.

File: pkg/controller/command/sdscomm/sdscomm.go (hunk 3 above)
Comment (DRK3) [reply pkg/controller/command/sdscomm/sdscomm.go]: (just removed the log line - didn't mean to commit that...)

File: cmd/user-agent/src/main.js (hunk 1 above)
Comment (DRK3) [reply cmd/user-agent/src/main.js:73]: @sudeshrshetty Note that at least some of the edge-agent functionality works without those other opts (but with the SDS URL). I tested registering wallet and DID creation and they seemed to work ok.

I can leave it as blank URL if you'd really prefer that - I just figured that it's a little more convenient so that you can do UI/JS work quickly. At least now with this change you'll get a more obvious error message.

Comment (llorllale) [reply cmd/user-agent/src/main.js:73]: Yeah I am trying to understand what @sudeshrshetty is saying.... I see that `trustblocStartupOpts()` pulls the config from the backend... yet still uses `defaultTrustBlocStartupOpts` if `walletMediatorURL` is not present...

So `defaultTrustBlocstartupOpts` is the *fallback* and should definitely have *something* there. Config optional in the backend, mandatory in the frontend, from the looks of it.

Comment (sudeshrshetty) [reply cmd/user-agent/src/main.js:73]: I agree @llorllale , then we should initialize it with default options for all mandatory options.

File: pkg/controller/command/didclient/command.go (hunk 2 above)
Comment (sudeshrshetty) [reply pkg/controller/command/didclient/command.go:153]: Are you sure it creates new command object for each call??
Still, you should move this to constructor(New()) function

File: cmd/user-agent/src/main.js (hunk 1 above)
Comment (DRK3) [reply cmd/user-agent/src/main.js:73]: @sudeshrshetty Should I create a follow-up story for that and leave the `https://localhost:8072/encrypted-data-vaults` arg as is?

File: pkg/controller/command/didclient/command.go (hunk 2 above)
Comment (DRK3) [reply pkg/controller/command/didclient/command.go:153]: @sudeshrshetty Yeah, I actually did some testing since I was curious about exactly this... in fact, controller.GetCommandHandlers inside the addTrustBlocAgentHandlers function seemed to be called new every time I clicked...

Since this change seems unrelated to the current PR and will cause merge conflicts with the other PR, I'll fix this in a separate PR after my current two PRs are merged in. #267

Comment (DRK3) [reply pkg/controller/command/didclient/command.go:153]: Clarification: I tested this with the Create DID button on the DID management page

File: cmd/user-agent/src/main.js (hunk 1 above)
Comment (sudeshrshetty) [reply cmd/user-agent/src/main.js:73]: @DRK3 not needed for now
