### PR TITLE
fix: Store vc directly in indexeddb

### LINKED ISSUE #43: Store vc directly in indexeddb

### PR DESCRIPTION
**Pull request by fqutishat**
closes #43

Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>

### CODE REVIEW

File: pkg/store/vc/store.go [hunk 1]
```diff
@@ -64,20 +58,21 @@ func (c *callback) storeVC(this js.Value, inputs []js.Value) interface{} {
...
+
+		var vcMap map[string]interface{}
+		if err := json.Unmarshal([]byte(vcData), &vcMap); err != nil {
+			m["data"] = fmt.Sprintf("failed to unmarshal vc json: %s", err.Error())
 			inputs[0].Call("respondWith", js.Global().Get("Promise").Call("resolve", m))
 			return
 		}
 
-		if err := c.store.SaveVC(vc); err != nil {
+		if err := c.vcStore.Put(vcMap["id"].(string), []byte(vcData)); err != nil {
```
Comment (sandrask) [inline pkg/store/vc/store.go]: you should check if id exists here

Comment (fqutishat) [reply pkg/store/vc/store.go]: done
