### PR TITLE
fix: Check the user's session cookie before redirecting to the OIDC

### LINKED ISSUE #497: bug: /oidc/login does not check the user's session cookie before redirecting to the OIDC provider
https://github.com/llorllale/edge-agent/blob/ffd33ea110d37b9d129340d1420bd5e2496553f4/pkg/restapi/oidc/operations.go#L157

To reproduce:

* Clear cookies
* Open two tabs and navigate to the login page on both
* Login via one tab
* Login via the other tab

The second login should not have been allowed. Instead, the user should have been redirected to the dashboard.

Make sure a note is added to the demo docs indicating that different browsers/browser-containers are required in the 2-agent demo.

### PR DESCRIPTION
**Pull request by soluchok**
Check the user's session cookie before redirecting to the OIDC.

Closes #497 

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

### CODE REVIEW

**Review by rolsonquadras — APPROVED** [review]

**Review by fqutishat — APPROVED** [review]

File: pkg/restapi/oidc/operations.go [hunk 1]
```diff
@@ -165,6 +165,13 @@ func (o *Operation) oidcLoginHandler(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
+	_, found := session.Get(userSubCookieName)
+	if found {
+		http.Redirect(w, r, o.walletDashboard, http.StatusMovedPermanently)
```
Comment (llorllale) [inline pkg/restapi/oidc/operations.go:170]: @soluchok status code should not be MovedPermanently. Should use `http.StatusFound`
