### PR TITLE
fix: use KMS capability for OPS keyserver operations

### LINKED ISSUE #546: Missing zcap in call to update EDV capability in ops key server
https://github.com/trustbloc/edge-agent/blob/e84be2213851d0a9739f2c9a6a3ad966f1224c2f/pkg/restapi/oidc/operations.go#L587-L593

The ops key server's endpoint to update the EDV capability is protected with zcapld. Need to properly invoke the capability obtained when creating the ops key store.

EDIT: fix this logger's name while you're at it: https://github.com/trustbloc/edge-agent/blob/e84be2213851d0a9739f2c9a6a3ad966f1224c2f/pkg/restapi/oidc/operations.go#L73

### LINKED ISSUE #580: Authz Oathkeeper zcap signing fails
url - https://demo-oathkeeper-auth-keyserver.trustbloc.local:4461
error - {"error":{"code":401,"status":"Unauthorized","message":"The request could not be authorized"}}

### PR DESCRIPTION
**Pull request by llorllale**
closes #546
closes #580 

----

blocked by:
- [X]  https://github.com/trustbloc/hub-kms/pull/123
- [x]  https://github.com/trustbloc/agent-sdk/pull/113

-----

changes:

* use KMS capability for OPS keyserver operations
* update hub-kms image in tests/demo
* enable zcaps authz for hub-kms in tests/demo
* **temporarily sending access_token and ops keyserver zcap to the frontend to enable both key servers to be used there** (see TODO #583 )

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

File: pkg/restapi/oidc/operations.go [hunk 1]
```diff
@@ -757,6 +783,31 @@ func updateEDVCapabilityInKeyStore(baseURL, keystoreID, controller, vaultID stri
...
+	}
+
+	r.Header.Set(
+		zcapld.CapabilityInvocationHTTPHeader,
+		fmt.Sprintf(`zcap capability="%s",action="%s"`, compressedKMSCapability, action),
+	)
+
+	hs := httpsignatures.NewHTTPSignatures(&zcapld.AriesDIDKeySecrets{})
+	hs.SetSignatureHashAlgorithm(&zcapld.AriesDIDKeySignatureHashAlgorithm{
+		KMS:    &zcapRemoteKMS{},
```
Comment (Baha-sk) [inline pkg/restapi/oidc/operations.go:799]: if kms is not used here, then don't set KMS field. There's no need to create an empty zcapRemoteKMS implementation.

Comment (llorllale) [reply pkg/restapi/oidc/operations.go:799]: @Baha-sk it is used: https://github.com/trustbloc/edge-agent/blob/10062645befa4e3857f53096d81e91c96cc162f4/pkg/restapi/oidc/webkms.go#L24-L26

**Review by fqutishat — APPROVED** [review]

**Review by Baha-sk — APPROVED** [review]
