### PR TITLE
fix: Replace mem with persistant store in wallet-server start up

### LINKED ISSUE #608: Replace mem with persistant store in wallet-server start up

### PR DESCRIPTION
**Pull request by talwinder50**
closes #608

Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

### CODE REVIEW

File: cmd/wallet-server/startcmd/start.go [hunk 1]
```diff
@@ -75,11 +78,30 @@ const (
...
+	datasourceTimeoutDefault = 30
+
 	oidcBasePath    = "/oidc/"
 	healthCheckPath = "/healthcheck"
 	deviceBasePath  = "/device/"
 )
 
+const (
+	sleep = 1 * time.Second
+)
```
Comment (soluchok) [inline cmd/wallet-server/startcmd/start.go:103]: psl one line `const sleep = time.Second`

**Review by soluchok — APPROVED** [review]

**Review by sudeshrshetty — APPROVED** [review]
